//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    
    public partial class ClassListItem
    {
        public int ClassId { get; set; }
        public bool IsLike { get; set; }
        public int Member_Id { get; set; }
        public string Cover { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public Nullable<decimal> PosX { get; set; }
        public Nullable<decimal> PosY { get; set; }
        public string Title { get; set; }
        public int LikeNum { get; set; }
        public byte Level { get; set; }
        public string Avatar { get; set; }
        public int ReviewNum { get; set; }
        public int ClassNum { get; set; }
        public String CityName { get; set; }
        
    }
}
