//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;

    public partial class MemberReviewItem
    {
        public int ReviewId { get; set; }
        public string Comment { get; set; }
        public Nullable<byte> FeedBack { get; set; }
        public String CreatedDate { get; set; }
        public string Avatar { get; set; }
        public int MemberId { get; set; }
        public string Name { get; set; }
        public Byte TabId { get; set; }
        public string Title { get; set; }
        public int ClassId { get; set; }
    }
}
