//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    
    public partial class MessageListItem
    {
        public int MessageId { get; set; }
        public int From_Id { get; set; }
        public int To_Id { get; set; }
        public string MessageText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public int UnReadNumber { get; set; }
    }
}
