//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityInfo
    {
        public int CityId { get; set; }
        public string LocaleCode { get; set; }
        public string CityName { get; set; }
        public string CityKey { get; set; }
        public byte OrderRank { get; set; }
    }
}
