//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsShow { get; set; }
        public int Class_Id { get; set; }
        public int Member_Id { get; set; }
        public string CommentText { get; set; }
    }
}
