//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteId { get; set; }
        public int RelatedId { get; set; }
        public bool IsLike { get; set; }
        public bool IsFavorite { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int MemberId { get; set; }
        public byte FavoriteType { get; set; }
    }
}
