//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInfo
    {
        public int MemberId { get; set; }
        public byte SocialType { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public decimal PosX { get; set; }
        public decimal PosY { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool Gender { get; set; }
        public int Coins { get; set; }
        public int CoinsLocked { get; set; }
        public string Avatar { get; set; }
        public string SelfIntro { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string OpenId { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Etag { get; set; }
        public string Address { get; set; }
        public string SocialAccount { get; set; }
        public string ContactName { get; set; }
        public byte VerifyTag { get; set; }
        public byte NotifyTag { get; set; }
        public int Credit { get; set; }
        public string Pass { get; set; }
        public string DeviceToken { get; set; }
        public string AccessToken { get; set; }
        public string UnionId { get; set; }
        public string OpenId1 { get; set; }
        public string RCToken { get; set; }
        public bool IsLike { get; set; }
        public string ExtraInfo { get; set; }
    }
}
