//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaTag
    {
        public int MetaId { get; set; }
        public string MetaKey { get; set; }
        public int TitleBlurb { get; set; }
        public int KeywordsBlurb { get; set; }
        public int DescriptionBlurb { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
