//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    
    public partial class RecommendationItem
    {
        public byte GroupId { get; set; }
        public int Rank { get; set; }
        public bool IsShow { get; set; }
    }
}
