//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    
    public partial class ReportNumItem
    {
        public int Num1 { get; set; }
        public int Num2 { get; set; }
        public decimal Percentage { get; set; }
        public int RowNum { get; set; }
    }
}
