//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CategoryPopTag> CategoryPopTag { get; set; }
        public DbSet<CityInfo> CityInfo { get; set; }
        public DbSet<CoinsHistory> CoinsHistory { get; set; }
        public DbSet<EmailAccount> EmailAccount { get; set; }
        public DbSet<EmailTemplate> EmailTemplate { get; set; }
        public DbSet<MemberInfo> MemberInfo { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<MetaTag> MetaTag { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<SkillCategory> SkillCategory { get; set; }
        public DbSet<StudentReview> StudentReview { get; set; }
        public DbSet<TeacherReview> TeacherReview { get; set; }
        public DbSet<ClassInfo> ClassInfo { get; set; }
        public DbSet<BlurbsMain> BlurbsMain { get; set; }
        public DbSet<Favorite> Favorites { get; set; }
        public DbSet<ClassEditInfo> ClassEditInfoes { get; set; }
    
        public virtual ObjectResult<Blurbs_LoadByLanguageSiteVersion_p_Result> Blurbs_LoadByLanguageSiteVersion_p(string language, Nullable<byte> version)
        {
            var languageParameter = language != null ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(string));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("Version", version) :
                new ObjectParameter("Version", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Blurbs_LoadByLanguageSiteVersion_p_Result>("Blurbs_LoadByLanguageSiteVersion_p", languageParameter, versionParameter);
        }
    
        public virtual ObjectResult<CategoryPopTag_Load_p_Result> CategoryPopTag_Load_p()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CategoryPopTag_Load_p_Result>("CategoryPopTag_Load_p");
        }
    
        public virtual int CategoryPopTag_Save_p(Nullable<short> minToAdd)
        {
            var minToAddParameter = minToAdd.HasValue ?
                new ObjectParameter("MinToAdd", minToAdd) :
                new ObjectParameter("MinToAdd", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CategoryPopTag_Save_p", minToAddParameter);
        }
    
        public virtual ObjectResult<CityInfo_LoadAll_p_Result> CityInfo_LoadAll_p()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityInfo_LoadAll_p_Result>("CityInfo_LoadAll_p");
        }
    
        public virtual int ClassInfo_Add_p(Nullable<int> memberId, Nullable<int> categoryId, Nullable<byte> teache, Nullable<byte> skill, ObjectParameter paraId, ObjectParameter isExist)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("MemberId", memberId) :
                new ObjectParameter("MemberId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var teacheParameter = teache.HasValue ?
                new ObjectParameter("Teache", teache) :
                new ObjectParameter("Teache", typeof(byte));
    
            var skillParameter = skill.HasValue ?
                new ObjectParameter("Skill", skill) :
                new ObjectParameter("Skill", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClassInfo_Add_p", memberIdParameter, categoryIdParameter, teacheParameter, skillParameter, paraId, isExist);
        }
    
        public virtual ObjectResult<ClassInfo_Load_p_Result> ClassInfo_Load_p(Nullable<byte> loadBy, Nullable<int> paraId, Nullable<int> memberId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassInfo_Load_p_Result>("ClassInfo_Load_p", loadByParameter, paraIdParameter, memberIdParameter);
        }
    
        public virtual ObjectResult<ClassInfo_LoadAll_p_Result> ClassInfo_LoadAll_p(Nullable<byte> loadBy, Nullable<int> paraId, Nullable<byte> categoryId, Nullable<bool> isParentCate, Nullable<int> city, string keyword, Nullable<int> pageSize, Nullable<int> pageId, ObjectParameter resultNum)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("LoadBy", loadBy) :
                new ObjectParameter("LoadBy", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(byte));
    
            var isParentCateParameter = isParentCate.HasValue ?
                new ObjectParameter("IsParentCate", isParentCate) :
                new ObjectParameter("IsParentCate", typeof(bool));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageIdParameter = pageId.HasValue ?
                new ObjectParameter("PageId", pageId) :
                new ObjectParameter("PageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassInfo_LoadAll_p_Result>("ClassInfo_LoadAll_p", loadByParameter, paraIdParameter, categoryIdParameter, isParentCateParameter, cityParameter, keywordParameter, pageSizeParameter, pageIdParameter, resultNum);
        }
    
        public virtual int ClassInfo_Save_p(Nullable<int> paraId, string txtValue, Nullable<byte> paraValue, Nullable<bool> isValue, Nullable<byte> saveType)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            var txtValueParameter = txtValue != null ?
                new ObjectParameter("TxtValue", txtValue) :
                new ObjectParameter("TxtValue", typeof(string));
    
            var paraValueParameter = paraValue.HasValue ?
                new ObjectParameter("ParaValue", paraValue) :
                new ObjectParameter("ParaValue", typeof(byte));
    
            var isValueParameter = isValue.HasValue ?
                new ObjectParameter("IsValue", isValue) :
                new ObjectParameter("IsValue", typeof(bool));
    
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("SaveType", saveType) :
                new ObjectParameter("SaveType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClassInfo_Save_p", paraIdParameter, txtValueParameter, paraValueParameter, isValueParameter, saveTypeParameter);
        }
    
        public virtual int ClassNum_Load_p(Nullable<int> member, Nullable<int> @class, ObjectParameter classNum, ObjectParameter result2, ObjectParameter result3, ObjectParameter result4)
        {
            var memberParameter = member.HasValue ?
                new ObjectParameter("member", member) :
                new ObjectParameter("member", typeof(int));
    
            var classParameter = @class.HasValue ?
                new ObjectParameter("class", @class) :
                new ObjectParameter("class", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClassNum_Load_p", memberParameter, classParameter, classNum, result2, result3, result4);
        }
    
        public virtual int EmailAccount_Save_p(string mail, string name)
        {
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmailAccount_Save_p", mailParameter, nameParameter);
        }
    
        public virtual int MemberInfo_Add_p(string socialId, Nullable<byte> sType, ObjectParameter id, Nullable<int> city, string mail, string memberName, string avatarPath, string etag, ObjectParameter result)
        {
            var socialIdParameter = socialId != null ?
                new ObjectParameter("SocialId", socialId) :
                new ObjectParameter("SocialId", typeof(string));
    
            var sTypeParameter = sType.HasValue ?
                new ObjectParameter("SType", sType) :
                new ObjectParameter("SType", typeof(byte));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var avatarPathParameter = avatarPath != null ?
                new ObjectParameter("AvatarPath", avatarPath) :
                new ObjectParameter("AvatarPath", typeof(string));
    
            var etagParameter = etag != null ?
                new ObjectParameter("Etag", etag) :
                new ObjectParameter("Etag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MemberInfo_Add_p", socialIdParameter, sTypeParameter, id, cityParameter, mailParameter, memberNameParameter, avatarPathParameter, etagParameter, result);
        }
    
        public virtual int MemberInfo_Save_p(Nullable<byte> saveType, Nullable<int> id, Nullable<bool> isMale, string mail, string phoneNo, Nullable<int> city, string memberName, string intro, ObjectParameter result, Nullable<decimal> x, Nullable<decimal> y, Nullable<System.DateTime> birthday, string img)
        {
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("SaveType", saveType) :
                new ObjectParameter("SaveType", typeof(byte));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var isMaleParameter = isMale.HasValue ?
                new ObjectParameter("IsMale", isMale) :
                new ObjectParameter("IsMale", typeof(bool));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var phoneNoParameter = phoneNo != null ?
                new ObjectParameter("PhoneNo", phoneNo) :
                new ObjectParameter("PhoneNo", typeof(string));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var introParameter = intro != null ?
                new ObjectParameter("Intro", intro) :
                new ObjectParameter("Intro", typeof(string));
    
            var xParameter = x.HasValue ?
                new ObjectParameter("X", x) :
                new ObjectParameter("X", typeof(decimal));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("Y", y) :
                new ObjectParameter("Y", typeof(decimal));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var imgParameter = img != null ?
                new ObjectParameter("Img", img) :
                new ObjectParameter("Img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MemberInfo_Save_p", saveTypeParameter, idParameter, isMaleParameter, mailParameter, phoneNoParameter, cityParameter, memberNameParameter, introParameter, result, xParameter, yParameter, birthdayParameter, imgParameter);
        }
    
        public virtual ObjectResult<Message_LoadByFromAndToId_p_Result> Message_LoadByFromAndToId_p(Nullable<int> memberId1, Nullable<int> memberId2)
        {
            var memberId1Parameter = memberId1.HasValue ?
                new ObjectParameter("MemberId1", memberId1) :
                new ObjectParameter("MemberId1", typeof(int));
    
            var memberId2Parameter = memberId2.HasValue ?
                new ObjectParameter("MemberId2", memberId2) :
                new ObjectParameter("MemberId2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Message_LoadByFromAndToId_p_Result>("Message_LoadByFromAndToId_p", memberId1Parameter, memberId2Parameter);
        }
    
        public virtual ObjectResult<Message_LoadByMemberId_p_Result> Message_LoadByMemberId_p(Nullable<int> paraId)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Message_LoadByMemberId_p_Result>("Message_LoadByMemberId_p", paraIdParameter);
        }
    
        public virtual ObjectResult<Message_LoadUnReadNo_p_Result> Message_LoadUnReadNo_p(Nullable<int> memberId)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("MemberId", memberId) :
                new ObjectParameter("MemberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Message_LoadUnReadNo_p_Result>("Message_LoadUnReadNo_p", memberIdParameter);
        }
    
        public virtual int Message_Save_p(Nullable<int> fromId, Nullable<int> toId, string message, Nullable<byte> saveType, ObjectParameter id)
        {
            var fromIdParameter = fromId.HasValue ?
                new ObjectParameter("FromId", fromId) :
                new ObjectParameter("FromId", typeof(int));
    
            var toIdParameter = toId.HasValue ?
                new ObjectParameter("ToId", toId) :
                new ObjectParameter("ToId", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("SaveType", saveType) :
                new ObjectParameter("SaveType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Message_Save_p", fromIdParameter, toIdParameter, messageParameter, saveTypeParameter, id);
        }
    
        public virtual ObjectResult<Order_Load_p_Result> Order_Load_p(Nullable<byte> loadType, Nullable<int> paraId)
        {
            var loadTypeParameter = loadType.HasValue ?
                new ObjectParameter("loadType", loadType) :
                new ObjectParameter("loadType", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_Load_p_Result>("Order_Load_p", loadTypeParameter, paraIdParameter);
        }
    
        public virtual ObjectResult<Order_LoadByStudent_p_Result> Order_LoadByStudent_p(Nullable<int> paraId, Nullable<bool> isCheck)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            var isCheckParameter = isCheck.HasValue ?
                new ObjectParameter("isCheck", isCheck) :
                new ObjectParameter("isCheck", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_LoadByStudent_p_Result>("Order_LoadByStudent_p", paraIdParameter, isCheckParameter);
        }
    
        public virtual ObjectResult<Order_LoadByTeacher_p_Result> Order_LoadByTeacher_p(Nullable<int> paraId, Nullable<bool> isCheck)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            var isCheckParameter = isCheck.HasValue ?
                new ObjectParameter("isCheck", isCheck) :
                new ObjectParameter("isCheck", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_LoadByTeacher_p_Result>("Order_LoadByTeacher_p", paraIdParameter, isCheckParameter);
        }
    
        public virtual int Order_Save_p(Nullable<int> studentId, Nullable<int> classId, Nullable<int> status, Nullable<System.DateTime> classDate, string comment, Nullable<byte> saveType, ObjectParameter paraId, ObjectParameter result)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("studentId", studentId) :
                new ObjectParameter("studentId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var classDateParameter = classDate.HasValue ?
                new ObjectParameter("classDate", classDate) :
                new ObjectParameter("classDate", typeof(System.DateTime));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("saveType", saveType) :
                new ObjectParameter("saveType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Order_Save_p", studentIdParameter, classIdParameter, statusParameter, classDateParameter, commentParameter, saveTypeParameter, paraId, result);
        }
    
        public virtual int OrderCoin_Update_p(Nullable<int> paraId, Nullable<byte> status, Nullable<int> studentId, Nullable<int> teacherId, ObjectParameter result)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(byte));
    
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("studentId", studentId) :
                new ObjectParameter("studentId", typeof(int));
    
            var teacherIdParameter = teacherId.HasValue ?
                new ObjectParameter("teacherId", teacherId) :
                new ObjectParameter("teacherId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrderCoin_Update_p", paraIdParameter, statusParameter, studentIdParameter, teacherIdParameter, result);
        }
    
        public virtual ObjectResult<SkillCategory_LoadAll_p_Result> SkillCategory_LoadAll_p()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SkillCategory_LoadAll_p_Result>("SkillCategory_LoadAll_p");
        }
    
        public virtual ObjectResult<StudentReview_Load_p_Result> StudentReview_Load_p(Nullable<byte> loadBy, Nullable<int> paraId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentReview_Load_p_Result>("StudentReview_Load_p", loadByParameter, paraIdParameter);
        }
    
        public virtual int StudentReview_Save_p(Nullable<int> orderId, Nullable<int> classId, Nullable<int> scoreA, Nullable<int> scoreB, Nullable<int> scoreC, Nullable<byte> feedBack, string comment, ObjectParameter paraId, string priComment)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var scoreAParameter = scoreA.HasValue ?
                new ObjectParameter("scoreA", scoreA) :
                new ObjectParameter("scoreA", typeof(int));
    
            var scoreBParameter = scoreB.HasValue ?
                new ObjectParameter("scoreB", scoreB) :
                new ObjectParameter("scoreB", typeof(int));
    
            var scoreCParameter = scoreC.HasValue ?
                new ObjectParameter("scoreC", scoreC) :
                new ObjectParameter("scoreC", typeof(int));
    
            var feedBackParameter = feedBack.HasValue ?
                new ObjectParameter("feedBack", feedBack) :
                new ObjectParameter("feedBack", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var priCommentParameter = priComment != null ?
                new ObjectParameter("priComment", priComment) :
                new ObjectParameter("priComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StudentReview_Save_p", orderIdParameter, classIdParameter, scoreAParameter, scoreBParameter, scoreCParameter, feedBackParameter, commentParameter, paraId, priCommentParameter);
        }
    
        public virtual ObjectResult<TeacherReview_Load_p_Result> TeacherReview_Load_p(Nullable<int> loadBy, Nullable<int> paraId, Nullable<int> maxId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(int));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            var maxIdParameter = maxId.HasValue ?
                new ObjectParameter("maxId", maxId) :
                new ObjectParameter("maxId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TeacherReview_Load_p_Result>("TeacherReview_Load_p", loadByParameter, paraIdParameter, maxIdParameter);
        }
    
        public virtual int TeacherReview_Save_p(Nullable<int> orderId, Nullable<byte> feedBack, string comment, ObjectParameter paraId, string priComment)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            var feedBackParameter = feedBack.HasValue ?
                new ObjectParameter("feedBack", feedBack) :
                new ObjectParameter("feedBack", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var priCommentParameter = priComment != null ?
                new ObjectParameter("priComment", priComment) :
                new ObjectParameter("priComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TeacherReview_Save_p", orderIdParameter, feedBackParameter, commentParameter, paraId, priCommentParameter);
        }
    
        public virtual int StudentReview_LoadAll_p(Nullable<byte> loadBy, Nullable<int> classId, Nullable<int> memberId, Nullable<int> maxId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var maxIdParameter = maxId.HasValue ?
                new ObjectParameter("maxId", maxId) :
                new ObjectParameter("maxId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StudentReview_LoadAll_p", loadByParameter, classIdParameter, memberIdParameter, maxIdParameter);
        }
    
        public virtual int OrderStatus_ListHandler_p(Nullable<int> memberId)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrderStatus_ListHandler_p", memberIdParameter);
        }
    
        public virtual int Coin_Update_p(Nullable<byte> saveType, Nullable<int> memberId, Nullable<int> amount, ObjectParameter result)
        {
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("saveType", saveType) :
                new ObjectParameter("saveType", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Coin_Update_p", saveTypeParameter, memberIdParameter, amountParameter, result);
        }
    
        public virtual int Coin_UpdateTool_p(Nullable<byte> saveType, Nullable<int> memberId, Nullable<int> classId, Nullable<int> amount, ObjectParameter result)
        {
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("saveType", saveType) :
                new ObjectParameter("saveType", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Coin_UpdateTool_p", saveTypeParameter, memberIdParameter, classIdParameter, amountParameter, result);
        }
    
        public virtual ObjectResult<Notification_Load_p_Result> Notification_Load_p(Nullable<byte> loadBy, Nullable<int> memberId, Nullable<bool> checkStauts)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var checkStautsParameter = checkStauts.HasValue ?
                new ObjectParameter("checkStauts", checkStauts) :
                new ObjectParameter("checkStauts", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Notification_Load_p_Result>("Notification_Load_p", loadByParameter, memberIdParameter, checkStautsParameter);
        }
    
        public virtual ObjectResult<NotificationAlert_Load_p_Result> NotificationAlert_Load_p(Nullable<int> memberId, Nullable<bool> checkStauts)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var checkStautsParameter = checkStauts.HasValue ?
                new ObjectParameter("checkStauts", checkStauts) :
                new ObjectParameter("checkStauts", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotificationAlert_Load_p_Result>("NotificationAlert_Load_p", memberIdParameter, checkStautsParameter);
        }
    
        public virtual int Notification_Save_p(Nullable<byte> saveType, Nullable<int> memberId)
        {
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("saveType", saveType) :
                new ObjectParameter("saveType", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Notification_Save_p", saveTypeParameter, memberIdParameter);
        }
    
        public virtual int ClassNums_Load_p(Nullable<byte> loadType, Nullable<int> memberId, Nullable<int> classId, ObjectParameter resultNum1, ObjectParameter resultNum2, ObjectParameter resultNum3, ObjectParameter resultc1, ObjectParameter resultc2, ObjectParameter resultc3, ObjectParameter resulto1, ObjectParameter resulto2, ObjectParameter resulto3)
        {
            var loadTypeParameter = loadType.HasValue ?
                new ObjectParameter("loadType", loadType) :
                new ObjectParameter("loadType", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClassNums_Load_p", loadTypeParameter, memberIdParameter, classIdParameter, resultNum1, resultNum2, resultNum3, resultc1, resultc2, resultc3, resulto1, resulto2, resulto3);
        }
    
        public virtual int MemberNums_Load_p(Nullable<byte> loadType, Nullable<int> memberId, Nullable<int> classId, ObjectParameter resultNum1, ObjectParameter resultNum2, ObjectParameter resultNum3, ObjectParameter resultc1, ObjectParameter resultc2, ObjectParameter resultc3, ObjectParameter resulto1, ObjectParameter resulto2, ObjectParameter resulto3)
        {
            var loadTypeParameter = loadType.HasValue ?
                new ObjectParameter("loadType", loadType) :
                new ObjectParameter("loadType", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MemberNums_Load_p", loadTypeParameter, memberIdParameter, classIdParameter, resultNum1, resultNum2, resultNum3, resultc1, resultc2, resultc3, resulto1, resulto2, resulto3);
        }
    
        public virtual ObjectResult<ClassReview_Load_p_Result> ClassReview_Load_p(Nullable<byte> loadBy, Nullable<int> memberId, Nullable<int> classId, Nullable<byte> feedback, Nullable<int> maxId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var feedbackParameter = feedback.HasValue ?
                new ObjectParameter("feedback", feedback) :
                new ObjectParameter("feedback", typeof(byte));
    
            var maxIdParameter = maxId.HasValue ?
                new ObjectParameter("maxId", maxId) :
                new ObjectParameter("maxId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassReview_Load_p_Result>("ClassReview_Load_p", loadByParameter, memberIdParameter, classIdParameter, feedbackParameter, maxIdParameter);
        }
    
        public virtual ObjectResult<StudentReview_LoadByClass_p_Result> StudentReview_LoadByClass_p(Nullable<byte> loadBy, Nullable<int> memberId, Nullable<int> classId, Nullable<byte> feedback, Nullable<int> maxId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var feedbackParameter = feedback.HasValue ?
                new ObjectParameter("feedback", feedback) :
                new ObjectParameter("feedback", typeof(byte));
    
            var maxIdParameter = maxId.HasValue ?
                new ObjectParameter("maxId", maxId) :
                new ObjectParameter("maxId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentReview_LoadByClass_p_Result>("StudentReview_LoadByClass_p", loadByParameter, memberIdParameter, classIdParameter, feedbackParameter, maxIdParameter);
        }
    
        public virtual ObjectResult<StudentReview_LoadByMember_p_Result> StudentReview_LoadByMember_p(Nullable<byte> loadBy, Nullable<int> memberId, Nullable<byte> feedback, Nullable<int> maxId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var feedbackParameter = feedback.HasValue ?
                new ObjectParameter("feedback", feedback) :
                new ObjectParameter("feedback", typeof(byte));
    
            var maxIdParameter = maxId.HasValue ?
                new ObjectParameter("maxId", maxId) :
                new ObjectParameter("maxId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentReview_LoadByMember_p_Result>("StudentReview_LoadByMember_p", loadByParameter, memberIdParameter, feedbackParameter, maxIdParameter);
        }
    
        public virtual int Favorite_Save_p(Nullable<byte> saveType, Nullable<byte> favoriteType, Nullable<int> memberId, Nullable<int> paraId, Nullable<bool> isLike, Nullable<bool> isFavorite)
        {
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("saveType", saveType) :
                new ObjectParameter("saveType", typeof(byte));
    
            var favoriteTypeParameter = favoriteType.HasValue ?
                new ObjectParameter("favoriteType", favoriteType) :
                new ObjectParameter("favoriteType", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            var isLikeParameter = isLike.HasValue ?
                new ObjectParameter("isLike", isLike) :
                new ObjectParameter("isLike", typeof(bool));
    
            var isFavoriteParameter = isFavorite.HasValue ?
                new ObjectParameter("isFavorite", isFavorite) :
                new ObjectParameter("isFavorite", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Favorite_Save_p", saveTypeParameter, favoriteTypeParameter, memberIdParameter, paraIdParameter, isLikeParameter, isFavoriteParameter);
        }
    
        public virtual ObjectResult<ClassInfo_LoadByList_p_Result> ClassInfo_LoadByList_p(Nullable<byte> orderType, Nullable<byte> categoryId, Nullable<bool> isParentCate, Nullable<int> city, string keyword, Nullable<int> pageSize, Nullable<int> pageId, Nullable<decimal> posX, Nullable<decimal> posY, Nullable<int> memberId, ObjectParameter resultNum)
        {
            var orderTypeParameter = orderType.HasValue ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(byte));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(byte));
    
            var isParentCateParameter = isParentCate.HasValue ?
                new ObjectParameter("isParentCate", isParentCate) :
                new ObjectParameter("isParentCate", typeof(bool));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageIdParameter = pageId.HasValue ?
                new ObjectParameter("pageId", pageId) :
                new ObjectParameter("pageId", typeof(int));
    
            var posXParameter = posX.HasValue ?
                new ObjectParameter("posX", posX) :
                new ObjectParameter("posX", typeof(decimal));
    
            var posYParameter = posY.HasValue ?
                new ObjectParameter("posY", posY) :
                new ObjectParameter("posY", typeof(decimal));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassInfo_LoadByList_p_Result>("ClassInfo_LoadByList_p", orderTypeParameter, categoryIdParameter, isParentCateParameter, cityParameter, keywordParameter, pageSizeParameter, pageIdParameter, posXParameter, posYParameter, memberIdParameter, resultNum);
        }
    
        public virtual ObjectResult<ClassEditInfo_Load_p_Result> ClassEditInfo_Load_p(Nullable<byte> loadBy, Nullable<int> memberId, Nullable<int> classId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassEditInfo_Load_p_Result>("ClassEditInfo_Load_p", loadByParameter, memberIdParameter, classIdParameter);
        }
    
        public virtual int ClassEditInfo_Save_p(Nullable<int> paraId, string txtValue, Nullable<byte> paraValue, Nullable<bool> isValue, Nullable<byte> saveType)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            var txtValueParameter = txtValue != null ?
                new ObjectParameter("TxtValue", txtValue) :
                new ObjectParameter("TxtValue", typeof(string));
    
            var paraValueParameter = paraValue.HasValue ?
                new ObjectParameter("ParaValue", paraValue) :
                new ObjectParameter("ParaValue", typeof(byte));
    
            var isValueParameter = isValue.HasValue ?
                new ObjectParameter("IsValue", isValue) :
                new ObjectParameter("IsValue", typeof(bool));
    
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("SaveType", saveType) :
                new ObjectParameter("SaveType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClassEditInfo_Save_p", paraIdParameter, txtValueParameter, paraValueParameter, isValueParameter, saveTypeParameter);
        }
    }
}
