//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillCategory
    {
        public byte CategoryId { get; set; }
        public int Blurb_Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<byte> Parent_CategoryId { get; set; }
    }
}
