//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopBanner
    {
        public int BannerId { get; set; }
        public string BannerKey { get; set; }
        public string BannerImg { get; set; }
        public string Link { get; set; }
        public byte Rank { get; set; }
        public byte LinkType { get; set; }
    }
}
