//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlurbsMain
    {
        public int Id { get; set; }
        public int BlurbId { get; set; }
        public string BlurbText { get; set; }
        public byte SiteVersion { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
