//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBank.Site.DataSource.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BlurbsMain> BlurbsMain { get; set; }
        public DbSet<CategoryPopTag> CategoryPopTag { get; set; }
        public DbSet<CityInfo> CityInfo { get; set; }
        public DbSet<ClassInfo> ClassInfo { get; set; }
        public DbSet<CoinsHistory> CoinsHistory { get; set; }
        public DbSet<EmailTemplate> EmailTemplate { get; set; }
        public DbSet<MemberInfo> MemberInfo { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<MetaTag> MetaTag { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<SkillCategory> SkillCategory { get; set; }
        public DbSet<StudentReview> StudentReview { get; set; }
        public DbSet<TeacherReview> TeacherReview { get; set; }
    
        public virtual ObjectResult<Blurbs_LoadByLanguageSiteVersion_p_Result> Blurbs_LoadByLanguageSiteVersion_p(string language, Nullable<byte> version)
        {
            var languageParameter = language != null ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(string));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("Version", version) :
                new ObjectParameter("Version", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Blurbs_LoadByLanguageSiteVersion_p_Result>("Blurbs_LoadByLanguageSiteVersion_p", languageParameter, versionParameter);
        }
    
        public virtual ObjectResult<CategoryPopTag_Load_p_Result> CategoryPopTag_Load_p()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CategoryPopTag_Load_p_Result>("CategoryPopTag_Load_p");
        }
    
        public virtual int CategoryPopTag_Save_p(Nullable<short> minToAdd)
        {
            var minToAddParameter = minToAdd.HasValue ?
                new ObjectParameter("MinToAdd", minToAdd) :
                new ObjectParameter("MinToAdd", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CategoryPopTag_Save_p", minToAddParameter);
        }
    
        public virtual ObjectResult<CityInfo_LoadAll_p_Result> CityInfo_LoadAll_p()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityInfo_LoadAll_p_Result>("CityInfo_LoadAll_p");
        }
    
        public virtual int ClassInfo_Add_p(Nullable<int> memberId, Nullable<int> categoryId, Nullable<byte> teache, Nullable<byte> skill, ObjectParameter paraId, ObjectParameter isExist)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("MemberId", memberId) :
                new ObjectParameter("MemberId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var teacheParameter = teache.HasValue ?
                new ObjectParameter("Teache", teache) :
                new ObjectParameter("Teache", typeof(byte));
    
            var skillParameter = skill.HasValue ?
                new ObjectParameter("Skill", skill) :
                new ObjectParameter("Skill", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClassInfo_Add_p", memberIdParameter, categoryIdParameter, teacheParameter, skillParameter, paraId, isExist);
        }
    
        public virtual ObjectResult<ClassInfo_Load_p_Result> ClassInfo_Load_p(Nullable<byte> loadBy, Nullable<int> paraId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("LoadBy", loadBy) :
                new ObjectParameter("LoadBy", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassInfo_Load_p_Result>("ClassInfo_Load_p", loadByParameter, paraIdParameter);
        }
    
        public virtual ObjectResult<ClassInfo_LoadAll_p_Result> ClassInfo_LoadAll_p(Nullable<byte> loadBy, Nullable<byte> categoryId, Nullable<int> paraId, Nullable<int> city, string keyword)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("LoadBy", loadBy) :
                new ObjectParameter("LoadBy", typeof(byte));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassInfo_LoadAll_p_Result>("ClassInfo_LoadAll_p", loadByParameter, categoryIdParameter, paraIdParameter, cityParameter, keywordParameter);
        }
    
        public virtual int ClassInfo_Save_p(Nullable<int> paraId, string txtValue, Nullable<byte> paraValue, Nullable<bool> isValue, Nullable<byte> saveType)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            var txtValueParameter = txtValue != null ?
                new ObjectParameter("TxtValue", txtValue) :
                new ObjectParameter("TxtValue", typeof(string));
    
            var paraValueParameter = paraValue.HasValue ?
                new ObjectParameter("ParaValue", paraValue) :
                new ObjectParameter("ParaValue", typeof(byte));
    
            var isValueParameter = isValue.HasValue ?
                new ObjectParameter("IsValue", isValue) :
                new ObjectParameter("IsValue", typeof(bool));
    
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("SaveType", saveType) :
                new ObjectParameter("SaveType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClassInfo_Save_p", paraIdParameter, txtValueParameter, paraValueParameter, isValueParameter, saveTypeParameter);
        }
    
        public virtual int MemberInfo_Add_p(string socialId, Nullable<byte> sType, ObjectParameter id, Nullable<int> city, string mail, string memberName, ObjectParameter result)
        {
            var socialIdParameter = socialId != null ?
                new ObjectParameter("SocialId", socialId) :
                new ObjectParameter("SocialId", typeof(string));
    
            var sTypeParameter = sType.HasValue ?
                new ObjectParameter("SType", sType) :
                new ObjectParameter("SType", typeof(byte));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MemberInfo_Add_p", socialIdParameter, sTypeParameter, id, cityParameter, mailParameter, memberNameParameter, result);
        }
    
        public virtual ObjectResult<MemberInfo_Load_p_Result> MemberInfo_Load_p(Nullable<byte> loadBy, string account, Nullable<byte> type, Nullable<int> id)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("LoadBy", loadBy) :
                new ObjectParameter("LoadBy", typeof(byte));
    
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(byte));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MemberInfo_Load_p_Result>("MemberInfo_Load_p", loadByParameter, accountParameter, typeParameter, idParameter);
        }
    
        public virtual int MemberInfo_Save_p(Nullable<byte> saveType, Nullable<int> id, Nullable<bool> isMale, string mail, string phoneNo, Nullable<int> city, string memberName, string intro, ObjectParameter result, Nullable<decimal> x, Nullable<decimal> y, Nullable<System.DateTime> birthday, string img)
        {
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("SaveType", saveType) :
                new ObjectParameter("SaveType", typeof(byte));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var isMaleParameter = isMale.HasValue ?
                new ObjectParameter("IsMale", isMale) :
                new ObjectParameter("IsMale", typeof(bool));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var phoneNoParameter = phoneNo != null ?
                new ObjectParameter("PhoneNo", phoneNo) :
                new ObjectParameter("PhoneNo", typeof(string));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var introParameter = intro != null ?
                new ObjectParameter("Intro", intro) :
                new ObjectParameter("Intro", typeof(string));
    
            var xParameter = x.HasValue ?
                new ObjectParameter("X", x) :
                new ObjectParameter("X", typeof(decimal));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("Y", y) :
                new ObjectParameter("Y", typeof(decimal));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var imgParameter = img != null ?
                new ObjectParameter("Img", img) :
                new ObjectParameter("Img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MemberInfo_Save_p", saveTypeParameter, idParameter, isMaleParameter, mailParameter, phoneNoParameter, cityParameter, memberNameParameter, introParameter, result, xParameter, yParameter, birthdayParameter, imgParameter);
        }
    
        public virtual ObjectResult<Message_LoadByFromAndToId_p_Result> Message_LoadByFromAndToId_p(Nullable<int> memberId1, Nullable<int> memberId2)
        {
            var memberId1Parameter = memberId1.HasValue ?
                new ObjectParameter("MemberId1", memberId1) :
                new ObjectParameter("MemberId1", typeof(int));
    
            var memberId2Parameter = memberId2.HasValue ?
                new ObjectParameter("MemberId2", memberId2) :
                new ObjectParameter("MemberId2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Message_LoadByFromAndToId_p_Result>("Message_LoadByFromAndToId_p", memberId1Parameter, memberId2Parameter);
        }
    
        public virtual ObjectResult<Message_LoadByMemberId_p_Result> Message_LoadByMemberId_p(Nullable<int> paraId)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Message_LoadByMemberId_p_Result>("Message_LoadByMemberId_p", paraIdParameter);
        }
    
        public virtual ObjectResult<Message_LoadUnReadNo_p_Result> Message_LoadUnReadNo_p(Nullable<int> memberId)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("MemberId", memberId) :
                new ObjectParameter("MemberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Message_LoadUnReadNo_p_Result>("Message_LoadUnReadNo_p", memberIdParameter);
        }
    
        public virtual int Message_Save_p(Nullable<int> fromId, Nullable<int> toId, string message, Nullable<byte> saveType, ObjectParameter id)
        {
            var fromIdParameter = fromId.HasValue ?
                new ObjectParameter("FromId", fromId) :
                new ObjectParameter("FromId", typeof(int));
    
            var toIdParameter = toId.HasValue ?
                new ObjectParameter("ToId", toId) :
                new ObjectParameter("ToId", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("SaveType", saveType) :
                new ObjectParameter("SaveType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Message_Save_p", fromIdParameter, toIdParameter, messageParameter, saveTypeParameter, id);
        }
    
        public virtual ObjectResult<Order_Load_p_Result> Order_Load_p(Nullable<byte> loadType, Nullable<int> paraId)
        {
            var loadTypeParameter = loadType.HasValue ?
                new ObjectParameter("loadType", loadType) :
                new ObjectParameter("loadType", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_Load_p_Result>("Order_Load_p", loadTypeParameter, paraIdParameter);
        }
    
        public virtual ObjectResult<Order_LoadByStudent_p_Result> Order_LoadByStudent_p(Nullable<int> paraId)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_LoadByStudent_p_Result>("Order_LoadByStudent_p", paraIdParameter);
        }
    
        public virtual ObjectResult<Order_LoadByTeacher_p_Result> Order_LoadByTeacher_p(Nullable<int> paraId)
        {
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_LoadByTeacher_p_Result>("Order_LoadByTeacher_p", paraIdParameter);
        }
    
        public virtual int Order_Save_p(Nullable<int> studentId, Nullable<int> classId, Nullable<int> status, Nullable<System.DateTime> classDate, string comment, Nullable<byte> saveType, ObjectParameter paraId, ObjectParameter result)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("studentId", studentId) :
                new ObjectParameter("studentId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var classDateParameter = classDate.HasValue ?
                new ObjectParameter("classDate", classDate) :
                new ObjectParameter("classDate", typeof(System.DateTime));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var saveTypeParameter = saveType.HasValue ?
                new ObjectParameter("saveType", saveType) :
                new ObjectParameter("saveType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Order_Save_p", studentIdParameter, classIdParameter, statusParameter, classDateParameter, commentParameter, saveTypeParameter, paraId, result);
        }
    
        public virtual int OrderCoin_Update_p(Nullable<int> studentId, Nullable<int> paraId, Nullable<byte> status, ObjectParameter result)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("studentId", studentId) :
                new ObjectParameter("studentId", typeof(int));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrderCoin_Update_p", studentIdParameter, paraIdParameter, statusParameter, result);
        }
    
        public virtual ObjectResult<SkillCategory_LoadAll_p_Result> SkillCategory_LoadAll_p()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SkillCategory_LoadAll_p_Result>("SkillCategory_LoadAll_p");
        }
    
        public virtual ObjectResult<StudentReview_Load_p_Result> StudentReview_Load_p(Nullable<byte> loadBy, Nullable<int> paraId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentReview_Load_p_Result>("StudentReview_Load_p", loadByParameter, paraIdParameter);
        }
    
        public virtual ObjectResult<StudentReview_LoadByClass_p_Result> StudentReview_LoadByClass_p(Nullable<byte> loadBy, Nullable<int> classId, Nullable<byte> memberId, Nullable<byte> maxId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(byte));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(byte));
    
            var maxIdParameter = maxId.HasValue ?
                new ObjectParameter("maxId", maxId) :
                new ObjectParameter("maxId", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentReview_LoadByClass_p_Result>("StudentReview_LoadByClass_p", loadByParameter, classIdParameter, memberIdParameter, maxIdParameter);
        }
    
        public virtual int StudentReview_Save_p(Nullable<int> orderId, Nullable<int> scoreA, Nullable<int> scoreB, Nullable<int> scoreC, Nullable<byte> feedBack, string comment, ObjectParameter paraId, string priComment)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            var scoreAParameter = scoreA.HasValue ?
                new ObjectParameter("scoreA", scoreA) :
                new ObjectParameter("scoreA", typeof(int));
    
            var scoreBParameter = scoreB.HasValue ?
                new ObjectParameter("scoreB", scoreB) :
                new ObjectParameter("scoreB", typeof(int));
    
            var scoreCParameter = scoreC.HasValue ?
                new ObjectParameter("scoreC", scoreC) :
                new ObjectParameter("scoreC", typeof(int));
    
            var feedBackParameter = feedBack.HasValue ?
                new ObjectParameter("feedBack", feedBack) :
                new ObjectParameter("feedBack", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var priCommentParameter = priComment != null ?
                new ObjectParameter("priComment", priComment) :
                new ObjectParameter("priComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StudentReview_Save_p", orderIdParameter, scoreAParameter, scoreBParameter, scoreCParameter, feedBackParameter, commentParameter, paraId, priCommentParameter);
        }
    
        public virtual ObjectResult<TeacherReview_Load_p_Result> TeacherReview_Load_p(Nullable<int> loadBy, Nullable<int> paraId)
        {
            var loadByParameter = loadBy.HasValue ?
                new ObjectParameter("loadBy", loadBy) :
                new ObjectParameter("loadBy", typeof(int));
    
            var paraIdParameter = paraId.HasValue ?
                new ObjectParameter("paraId", paraId) :
                new ObjectParameter("paraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TeacherReview_Load_p_Result>("TeacherReview_Load_p", loadByParameter, paraIdParameter);
        }
    
        public virtual int TeacherReview_Save_p(Nullable<int> orderId, Nullable<byte> feedBack, string comment, ObjectParameter paraId, string priComment)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            var feedBackParameter = feedBack.HasValue ?
                new ObjectParameter("feedBack", feedBack) :
                new ObjectParameter("feedBack", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var priCommentParameter = priComment != null ?
                new ObjectParameter("priComment", priComment) :
                new ObjectParameter("priComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TeacherReview_Save_p", orderIdParameter, feedBackParameter, commentParameter, paraId, priCommentParameter);
        }
    }
}
